- HISTORY.md
- session/cookie.js
- test/cookie.js
This solves #432. I'm setting the `maxAge` with an environment variable which is parsed as a string. The PR adds a small fix to automatically convert strings to integers, as the error message is vague and creates confusion.
> Added fix for maxAge string unhandled type error

- README.md
There is atm no ArangoDB session storage in the list... added one I use right now
> Include ArangoDB Session storage in the list

- HISTORY.md
- session/cookie.js
- test/cookie.js
Hello. In new release you have an error:
`TypeError: Cannot set property data of #<Object> which has only a getter`
So, this happened because you've changed this code 
But in your `cookie.js` file `strict mode` is enabled. That is the reason why JS throws an error.
So I think the better way is to define setter for data field in prototype.
> TypeError: Cannot set property data of #<Object> which has only a getter fix

- HISTORY.md
- index.js
- session/memory.js
- test/session.js
I’m using SOA (Service Oriented Architecture) application. There I’m having different services that wroted on different languages. For store session I’m using Redis. In PHP and others applications I'm implementing express-session like handlers for share sessions between the services.
But I’m also using third party services, and they can generate broken session record without cookie section. If this section is missed, then all my Node.js applications are went down with error:
```js
node_modules/express-session/session/store.js:87
var expires = sess.cookie.expires
^
TypeError: Cannot read property 'expires' of undefined at RedisStore.Store.createSession
```
> Fix bug in cookie store

- HISTORY.md
- session/store.js
- test/session.js
- test/support/smart-store.js
If `expires` is a Date, then originalMaxAge is not restored and session is not being rolled.
> originalMaxAge should always be restored.

- HISTORY.md
- package.json
> bump cookie and safe buffer

- HISTORY.md
- index.js
- test/session.js
When `reload`'s callback is called, it invokes `wrapmethods` on the
request session, ensuring the new session's `reload` call is overriden
with a custom `reload`, calling the original. However, there's no
guarantee a new session is created, resulting in `reload` overriding
an overriden `reload`! Given enough such override-overrides, the stack
will overflow, gruesomely erupting into several hundreds of lines of
callstack, leaving the lonely developer to wonder how he has reached
such a mess, reflecting on several important life choices.
Note that the testing framework, for reasons beyond my current
comprehension, did not correctly act upon this `RangeError`. When
running the new test case without the fix, the `mocha` call hangs
seemingly indefinitely. That may be deserving of further …
> fix: reload calls exceeding stack track in case of errors

- test/cookie.js
- test/cookie.js fails intermittently `(59999 !== 60000)` when it checks the cookie's 'maxAge' against the value used when the cookie was created. Since this property is 'live', its current value (in ms) can occasionally decrease by the time the check is made. The test already deals with the (also live) 'expires' property in a similar way.
> allow tolerance when checking cookie's maxAge

- test/session.js
Change the call to use sid function
```javascript
.expect(shouldSetCookieToDifferentSessionId(sid(res)))
```
> fix: unit test when sid not in store

- README.md
After going over the readme connect modules section in order to find which were being downloaded the most the following were found to be deprecated
- [connect-mssql](https://www.npmjs.com/package/connect-mssql) ~100 weekly downloads
- [documentdb-session](https://www.npmjs.com/package/documentdb-session) ~80 weekly downloads
both are now deprecated
> docs: remove deprecated connect modules from README.md

- HISTORY.md
- index.js
- test/session.js
This adds a missing command to commit the progressive headers within `res.end` before attempting to read them. This has the standard side-effect of ensuring a second call to `res.end` will fail with a headers already set error. This is the same behavior other modules like `compression` does to get the headers set, same as the internal Node.js code of `res.end`.
Fixes #766
> Fix res.end patch to always commit headers

- README.md
This PR adds a link to a session store implementation for the [Prisma Framework](https://www.prisma.io) ([Github link](https://github.com/prisma/prisma)).
> Link to Prisma session store implementation

- .github/workflows/ci.yml
- test/session.js
With V8 9.3, the error message is: "Cannot read properties of undefined (reading 'expires')"
See https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2754/nodes=fedora-latest-x64/testReport/junit/(root)/citgm/express_session_v1_17_2/
> test: make tests pass on Node.js >=16.9.0

- HISTORY.md
- index.js
- test/session.js
When the `saveUninitialized` option is set to false, sessions will be
saved at the end of the request even when they have already been saved
earlier in the request and not subsequently modified. The result is a
double save that can potentially be wasteful with the persistence layer.
This change checks for modification of the session before saving, and
saves only if needed.
> fix: skip re-saving session when not modified since save

- HISTORY.md
- README.md
- package.json
- session/cookie.js
- test/cookie.js
- test/session.js
This adds cookie.priority by passing this property through to cookie (which requires us to upgrade cookie to >=0.5.0).
The priority option is not fully standardized, but has been proposed and in-use since 2016.
See also: https://github.com/jshttp/cookie/issues/138
Fixes: #884
> Add cookie.priority

- README.md
This npmjs package is dead for mysterious reasons.
https://www.npmjs.com/package/session-rethinkdb
Outside the fact is was abandoned for 6 years, it's no longer indexed on npmjs, you can access it only with the direct link.
The upstream repository disappeared too: https://github.com/llambda/session-rethinkdb.
There seems to be alternatives:
- https://www.npmjs.com/package/session-rethinkdb-ts
- https://www.npmjs.com/package/express-session-rethinkdb-esm
> README: remove rethinkDB

- HISTORY.md
- README.md
- package.json
- session/cookie.js
- test/cookie.js
- test/session.js
> Add "Partitioned" option to cookies

- index.js
- test/session.js
As part of removing deprecated features and dropping compatibility with *cookie-parse*
> feat: remove read signedCookies and cookies

- index.js
adds debug statements related to `Set-Cookie` and `issecure`, for additional visibility.
> additional debug statements

- index.js
With huge session object the hash method become slower because iterate on each key/value of the object, just for remove the cookie property on the first level!
This PR make hash method 2/3x faster!
Online [benchmark](https://perf.link/#eyJpZCI6Im41MnM4ZTkzdnIwIiwidGl0bGUiOiJGaW5kaW5nIG51bWJlcnMgaW4gYW4gYXJyYXkgb2YgMTAwMCIsImJlZm9yZSI6ImNvbnN0IHNlc3MgPSB7XG4gIHVzZXI6ICdTaW1vbmUnLFxuICBkYXRhOiB7IG5lc3RlZDoge30gfSxcbiAgY29va2llOiB7IG5hbWU6ICdhYmMxMjMnIH1cbn0iLCJ0ZXN0cyI6W3sibmFtZSI6IkZpbmQgaXRlbSAxMDAiLCJjb2RlIjoiY29uc3QgeyBjb29raWUsIC4uLnNlc3NXaXRob3V0Q29va2llIH0gPSBzZXNzO1xuY29uc3Qgc3RyID0gSlNPTi5zdHJpbmdpZnkoc2Vzc1dpdGhvdXRDb29raWUpOyIsInJ1bnMiOlszNzMwMDAsMTYyMDAwLDE4OTAwMCwzMzkwMDAsMTAwMCw4OTcwMDAsNDk5MDAwLDcwMDAwMCwxMzYwMDAsNjAwMDAsNTcyMDAwLDExNDAwMCwxMDAwLDExNjAwMCw0MDAwLDIwMDAwMCw1NDAw …
> perf: 2x faster hash stringify
